### ISSUE TITLE
Missing runs?

### ISSUE THREAD

**Issue by arjenpdevries** [castorini/TREC-COVID#11]
We didn't do that well but we're not in your CSV and we did not do that badly :-) How did you process the run files to create the CSV?

**Comment by lintool** [comment]
`leaderboard.csv` is simply a machine-readable of version of NIST's spreadsheet: https://docs.google.com/spreadsheets/d/e/2PACX-1vQF75pi8N4AdAE3or8XE7PjHtv5NbyHJeCdClvXO51eUWsww6qJABzJJ-4jQvQFxK4kMDTpSqcX6w6Z/pubhtml

See inclusion criteria in the spreadsheet itself.

**Comment by arjenpdevries** [comment]
Ah we did do that badly! Tnx, did not realize it is just "save as".
