### ISSUE TITLE
add contributed to judgment set

### ISSUE THREAD

**Issue by seanmacavaney** [castorini/TREC-COVID#2]
Is it worthwhile to add "contributed to judgment sets" to `round1/leaderboard.csv`? If you think so, I'll go ahead and add for everything that's there now.

**Comment by lintool** [comment]
yes - in the limit, we want to replicate everything in the PDFs, just a matter of needing hands to help with distributed data entry...

... and for all runs, also... I just got tired after the top 30.

**Comment by lintool** [comment]
Closed by #4
